name = "Contour"
uuid = "d38c429a-6771-53c6-b99e-75d170b6e991"
version = "0.6.3"

[compat]
julia = "0.7, 1"
Aqua = "0.8"
JET = "0.0.1, 0.4, 0.8"
LinearAlgebra = "1"
OffsetArrays = "1"
StaticArrays = "1"
StatsBase = "0.34"
Test = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "LinearAlgebra", "StatsBase", "Test", "OffsetArrays", "StaticArrays"]
